language: python

cache: ccache

sudo: false

python:
  - 3.6

addons:
  apt:
    packages:
      mlocate

env:
  global:
    - CONDA_DEPENDENCIES="nomkl scipy matplotlib"
    - MPLBACKEND=Agg
    - ASTROPY_CONDA=true
  matrix:
    # Make sure that the benchmarks don't completely crash for old versions of
    # Astropy - essentially make sure the imports don't cause the whole test
    # suite to not work.
    - ASTROPY_VERSION=dev
    - ASTROPY_VERSION=3.2
    - ASTROPY_VERSION=3.1
    - ASTROPY_VERSION=3.0
    - ASTROPY_VERSION=2.0
    - ASTROPY_CONDA=false CONDA_DEPENDENCIES=""

install:
  - git clone git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda.sh
  - pip install asv
  - asv machine --machine Travis --os unknown --arch unknown --cpu unknown --ram unknown

script:
  # NOTE: we deliberately don't use ASTROPY_VERSION=dev here because we want to
  # make sure that asv can install it by itself.
  - if [[ $ASTROPY_CONDA == false ]]; then
      asv run -q;
    else
      asv dev --strict;
    fi
